### ISSUE TITLE
Views and assets is not working on dist folder

### ISSUE THREAD

**Issue by calebeaires** [cdiaz/nestjs-auth0#1]
To make production folder (dist) I just type `tsc`, but `views` and some `assets` files does not goes to `dist` folder. How to make an production app that has views engine on nextjs.com project!

ps.: Good work here. I starterd my project from this repo!

**Comment by cdiaz** [comment]
hello @calebeaires, sorry for delay. 
You can use gulp, webpack, or simply create a script that copies the views and resources in the build, for now I implemented a simple [script](https://github.com/cdiaz/nestjs-auth0/blob/master/package.json#L13) on package.json
